### ISSUE TITLE
Kamisado hangs up

### ISSUE THREAD

**Issue by DS28** [GlukKazan/Dagaz#1]
When player make move that doesn't let computer make move - game hangs up.

For example - I play b1-b2:
![_2018-01-10_21-50-55](https://user-images.githubusercontent.com/13565834/34778612-5f619736-f650-11e7-9901-2e68db56cd88.png)

Computer can't move - I should move again?

**Comment by GlukKazan** [comment]
Hi, I know about this problem. 
I'll try to fix it soon. Thanks for this case.

**Comment by GlukKazan** [comment]
By the rules, in this case the Black passes the turn, and the White must continue the Yellow piece (the only move to the red square).

**Comment by GlukKazan** [comment]
Fixed: [4d02269](https://github.com/GlukKazan/Dagaz/commit/4d022699e459b73cd7cda11fd2f55a57b2d63e9d)
[641b09f](https://github.com/GlukKazan/GlukKazan.github.io/commit/641b09fe438228a0de6e2706443993545d69382d)
