### ISSUE TITLE
Any documents or tutorials ?

### ISSUE THREAD

**Issue by stepney141** [GlukKazan/Dagaz#2]
Hello.
I knew Dagaz Project through your articles such as [this one](https://habr.com/ru/post/481868/).
I am so interested in Dagaz and would like to try it myself, but I got confused at the usage of it (I have already checked [glukkazan.github.io](https://glukkazan.github.io/)). 
Do you have any detailed documents, tutorials, or descriptions about how to use Dagaz ?

**Comment by stepney141** [comment]
I think that this repository should at least contain a README.md file to explain what is the purpose of this repository. I would be happy if you check out my pull request.

**Comment by GlukKazan** [comment]
Hi

I'm grateful for your contribution. English is not my native language and I'm having problems with documentation.
Besides, I am constantly running out of time. I write a lot of articles, but I don't have enough time to document.
By the way, two articles in Russian and English will appear in the near future.

I would like to establish a correspondence with you by Email. My address: glukkazan@gmail.com
Perhaps I can help you with Dagaz if we communicate by mail.

**Comment by stepney141** [comment]
Thank you for your comment and kind support !
I'm not an native English speaker too (I'm Japanese), but I would like to help you with both of 
development and documentation as far as I can do.
I'll email you about Dagaz in a few weeks.
