### ISSUE TITLE
Fix Gess Rules

### ISSUE THREAD

**Issue by PraseodymiumSpike** [GlukKazan/Dagaz#6]
It appears you got the rules of Gess a bit wrong. According to Wikipedia, a Piece's Move must stop as soon as any of its Stones are off the board, but you only stop Pieces' Moves when the Piece's center is off the board. The same goes for when Pieces encounter other Stones during the course of a Move.
For example, the moves that are indicated with the three red arrows in this image should be illegal:
![image](https://user-images.githubusercontent.com/99032794/197585621-28bf0e92-4239-4461-8117-6392d7c70320.png)
On the other hand, the move indicated with the green arrow is correctly marked as legal.

**Comment by GlukKazan** [comment]
Thanks I will check it out.

**Comment by GlukKazan** [comment]
Fixed: https://github.com/GlukKazan/Dagaz/commit/520afb8fb54b5c3468f957b7d9b27e3e58e6e745
