### ISSUE TITLE
Annan Shogi Glitch

### ISSUE THREAD

**Issue by PraseodymiumSpike** [GlukKazan/Dagaz#7]
In Annan Shogi, the game does not end if the king is taken. Furthermore, moves that expose the king to check indirectly are allowed.

**Comment by GlukKazan** [comment]
For me, this is news and Wikipedia does not describe this rule. Can you clarify the source?

**Comment by PraseodymiumSpike** [comment]
I think you may have misunderstood me. The game as it appears on your website doesn't end if the king is taken and allows indirect self-checks, but the actual game should end if the king is taken and should not allow indirect self-checks.  I will briefly explain what I mean by an indirect self-check. Take a look at the following position:
![image](https://user-images.githubusercontent.com/99032794/211903836-77e0c3cf-7cb6-4bab-8447-e585f9ebe046.png)
The move marked with a sad face should be illegal, but it is allowed by the website. Take a look at what happens if this move is made.
![image](https://user-images.githubusercontent.com/99032794/211904195-ab8e4405-15d3-4ff7-a57e-8e5d384f4c64.png)
The king can be captured! Furthermore, if the king is captured in this way, the game does not end even though it should.

**Comment by GlukKazan** [comment]
Well, I'll take a look at this. Thanks for the information.

**Comment by GlukKazan** [comment]
Fixed: https://github.com/GlukKazan/Dagaz/commit/5ffc1632fb384e0653063031938f815839d36844
